<?php
/**
 * Implements hook_block_info().
 */
function zmodule2_block_info() {
  $blocks['zmodule2date'] = array(
    // The name that will appear in the block list.
    'info' => t('Zoroastrian module current date'),
    // Default setting.
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  $blocks['zmodule2pray'] = array(
    // The name that will appear in the block list.
    'info' => t('Zoroastrian module pray time'),
    // Default setting.
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  return $blocks;
}
/**
 * Implements hook_block_view().
 */
function zmodule2_block_view($delta = '') {
  switch ($delta) {
    case 'zmodule2date':
      $block['subject'] = t('Зороастрийская дата');
      if (user_access('access content')) {
        // Use our custom function to retrieve data.
        module_load_include('inc', 'zmodule2','zmodule2date');
        $block['content'] = zmodule2date();  
      }
      return $block;
    break;
    case 'zmodule2pray':
      $block['subject'] = t('Время молитвы');
      if (user_access('access content')) {
        // Use our custom function to retrieve data.
        module_load_include('inc', 'zmodule2','zmodule2pray');
        $block['content'] = zmodule2pray();  
      }
      return $block;
    break;
  }
  
}
/**
 * Implements hook_permission().
 */
function zmodule2_permission() {
  return array(
    'run zdate update' => array(
      'title' => t('Run update zoroastrian date'),
      'description' => t('Run update zoroastrian date'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function zmodule2_menu() {
  $items = array();

  $items['admin/config/content/zmodule2'] = array(
    'title' => 'Zmodule2 module',
    'description' => 'Configuration for zmodule2 module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('zmodule2_form'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/reports/zmodule2'] = array(
    'title' => 'Update zoroastrian date',
    'description' => 'Update zoroastrian date.',
    'page callback' => 'security_review_page',
    'access arguments' => array('access security review list'),
    'file' => 'zmodule2update.pages.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/reports/zmodule2/run'] = array(
    'title' => 'Update & view',
  //  'access arguments' => array('access security review list'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );

  return $items;
}
/**
 * Page callback: zmodule2 settings
 *
 * @see zmodule2_menu()
 */
function zmodule2_form($form, &$form_state) {
  $form['timezone'] = array(
    '#type' => 'textfield',
    '#title' => t('Временная зона'),
    '#default_value' => variable_get('timezone', 'Europe/Moscow'),
    '#description' => t('Место в котой будет считаться время.'),
    '#required' => TRUE,
  );
  $form['yeardelay'] = array(
    '#type' => 'textfield',
    '#title' => t('Смещение относительно рождества христова'),
    '#default_value' => variable_get('yeardelay', 1111),
    '#size' => 5,
    '#description' => t('Для годов 4000 равно 1111, для 1200 равно -800'),
    '#required' => TRUE,
  );
  $form['cityname'] = array(
    '#type' => 'textfield',
    '#title' => t('Наименование города'),
    '#default_value' => variable_get('cityname', "Санкт-Петербург"),
    '#description' => t('В котором будем считать восход'),
    '#required' => TRUE,
  );
  $form['latitude'] = array(
    '#type' => 'textfield',
    '#title' => t('Широта города'),
    '#default_value' => variable_get('latitude', 59.56),
    '#size' => 5,
    '#required' => TRUE,
  );
  $form['longtitude'] = array(
    '#type' => 'textfield',
    '#title' => t('Долгота города'),
    '#default_value' => variable_get('longtitude', 30.15),
    '#size' => 5,
    '#required' => TRUE,
  );
  $form['zenith'] = array(
    '#type' => 'textfield',
    '#title' => t('Зенит'),
    '#default_value' => variable_get('zenith', 90.583333),
    '#size' => 10,
    '#description' => t('Наивысшая воображаемая точка небесной сферы, находящаяся над головой наблюдателя'),
    '#required' => TRUE,
  );
  $form['gmtoffset'] = array(
    '#type' => 'textfield',
    '#title' => t('Разница времени от GMT'),
    '#default_value' => variable_get('timeoffset', 3),
    '#size' => 3,
    '#required' => TRUE,
  );

  return system_settings_form($form);
}


